### ISSUE TITLE
genesis: command not found

### ISSUE THREAD

**Issue by jjercTK** [tektonlabs/genesis-generator#19]
As pointed in the readme, I just run:
```
$ yarn global add genesis-generator
$ genesis empty-folder/
> genesis: command not found
```
Am I missing something?

**Comment by jopereyral** [comment]
@jjercTK  I'm going to work on that, and public 0.1.1 version :)

**Comment by jjercTK** [comment]
In my case, yarn wasn't installed properly. To fix it: `yarn global bin` and add it to your $PATH.
